### ISSUE TITLE
Set environment for back-end on app launch

### ISSUE THREAD

**Issue by twynb** [twynb/AudioStreamSplitting#95]
As of current, the environment variables aren't set in the back end when first launching the app. This is mostly a problem for the file name template because it does display an initial value, but that doesn't arrive at the back end until you click "Set".

**Comment by chubetho** [comment]
This problem does not occur anymore, right?

**Comment by twynb** [comment]
Correct, the template doesn't have a set button anymore either way (and i believe is sent with every save request?) so this is outdated.
